### ISSUE TITLE
Go for "Days since x per million confirmed" instead of "Days since 500 confirmed" as x-axis

### ISSUE THREAD

**Issue by aweisser** [paroj/arewedeadyet#3]
Would'nt it be even more comparable when also using numbers relative to the population as values for the x axis?
The countries should have taken counter measures after a certain percentage of its citizens became infected. 
500 infections in Switzerland is not the same as 500 infections in US.

**Comment by paroj** [comment]
Thats difficult to say I think, because e.g. 20 Infections **are** probably the same in the US and in Switzerland.
I arrived at 500 by trial and error as it makes different countries align nicely with China, which is nice to have as a reference.
Initially I set the threshold to 25, but that shifts countries that tested early, but the outbreak was late e.g. Germany.

However, I factored out the alignment function, so you can play with yourself:
https://github.com/paroj/arewedeadyet/blob/b4cc5fd2ea3a25c80abae6c714274ad5d87edf65/index.html#L164-L166

**Comment by aweisser** [comment]
I finally found some plots at Forbes that work this way:
https://www.forbes.com/sites/trevornace/2020/03/22/population-adjusted-coronavirus-cases-top-10-countries-compared/

**Comment by aweisser** [comment]
Here's the slightly different version: https://aweisser.github.io/arewedeadyet/

**Comment by darksylinc** [comment]
Anecdotal: Now that we're nearing the end of 2021; I find it'd be more useful to have just raw calendar dates.

The rationale is that it seems to be a very strong correlation between Winter (high peaks) and Summer (low peaks) when comparing countries in the northern vs southern hemisphere.

**Comment by paroj** [comment]
fixed https://paroj.github.io/arewedeadyet/monitor.html
